/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as AuthImport } from './routes/_auth'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedSearchByPayItemsImport } from './routes/_protected/search-by-pay-items'
import { Route as ProtectedSearchByBidsImport } from './routes/_protected/search-by-bids'
import { Route as ProtectedProfileImport } from './routes/_protected/profile'
import { Route as ProtectedBidGenerationImport } from './routes/_protected/bid-generation'
import { Route as ProtectedBidComparisonImport } from './routes/_protected/bid-comparison'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedSearchByPayItemsRoute = ProtectedSearchByPayItemsImport.update({
  path: '/search-by-pay-items',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedSearchByBidsRoute = ProtectedSearchByBidsImport.update({
  path: '/search-by-bids',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedProfileRoute = ProtectedProfileImport.update({
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedBidGenerationRoute = ProtectedBidGenerationImport.update({
  path: '/bid-generation',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedBidComparisonRoute = ProtectedBidComparisonImport.update({
  path: '/bid-comparison',
  getParentRoute: () => ProtectedRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_protected/bid-comparison': {
      preLoaderRoute: typeof ProtectedBidComparisonImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/bid-generation': {
      preLoaderRoute: typeof ProtectedBidGenerationImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/profile': {
      preLoaderRoute: typeof ProtectedProfileImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/search-by-bids': {
      preLoaderRoute: typeof ProtectedSearchByBidsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/search-by-pay-items': {
      preLoaderRoute: typeof ProtectedSearchByPayItemsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/': {
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([AuthSignInRoute]),
  ProtectedRoute.addChildren([
    ProtectedBidComparisonRoute,
    ProtectedBidGenerationRoute,
    ProtectedProfileRoute,
    ProtectedSearchByBidsRoute,
    ProtectedSearchByPayItemsRoute,
    ProtectedIndexRoute,
  ]),
])

/* prettier-ignore-end */
