/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as AuthImport } from './routes/_auth'
import { Route as AdminsRouteImport } from './routes/admins/route'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as AdminsCreateAccountImport } from './routes/admins/create-account'
import { Route as ProtectedProfileImport } from './routes/_protected/profile'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminsRouteRoute = AdminsRouteImport.update({
  path: '/admins',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const AdminsCreateAccountRoute = AdminsCreateAccountImport.update({
  path: '/create-account',
  getParentRoute: () => AdminsRouteRoute,
} as any)

const ProtectedProfileRoute = ProtectedProfileImport.update({
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admins': {
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_protected/profile': {
      preLoaderRoute: typeof ProtectedProfileImport
      parentRoute: typeof ProtectedImport
    }
    '/admins/create-account': {
      preLoaderRoute: typeof AdminsCreateAccountImport
      parentRoute: typeof AdminsRouteImport
    }
    '/_protected/': {
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AdminsRouteRoute.addChildren([AdminsCreateAccountRoute]),
  AuthRoute.addChildren([AuthSignInRoute]),
  ProtectedRoute.addChildren([ProtectedProfileRoute, ProtectedIndexRoute]),
])

/* prettier-ignore-end */
