/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as AuthImport } from './routes/_auth'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'
import { Route as ProtectedBidsRouteImport } from './routes/_protected/bids/route'
import { Route as ProtectedBidsIndexImport } from './routes/_protected/bids/index'
import { Route as ProtectedBidsBidGenerationImport } from './routes/_protected/bids/bid-generation'
import { Route as ProtectedBidsIdImport } from './routes/_protected/bids/$id'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const ProtectedBidsRouteRoute = ProtectedBidsRouteImport.update({
  path: '/bids',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedBidsIndexRoute = ProtectedBidsIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedBidsRouteRoute,
} as any)

const ProtectedBidsBidGenerationRoute = ProtectedBidsBidGenerationImport.update(
  {
    path: '/bid-generation',
    getParentRoute: () => ProtectedBidsRouteRoute,
  } as any,
)

const ProtectedBidsIdRoute = ProtectedBidsIdImport.update({
  path: '/$id',
  getParentRoute: () => ProtectedBidsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_protected/bids': {
      preLoaderRoute: typeof ProtectedBidsRouteImport
      parentRoute: typeof ProtectedImport
    }
    '/_auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_protected/': {
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/bids/$id': {
      preLoaderRoute: typeof ProtectedBidsIdImport
      parentRoute: typeof ProtectedBidsRouteImport
    }
    '/_protected/bids/bid-generation': {
      preLoaderRoute: typeof ProtectedBidsBidGenerationImport
      parentRoute: typeof ProtectedBidsRouteImport
    }
    '/_protected/bids/': {
      preLoaderRoute: typeof ProtectedBidsIndexImport
      parentRoute: typeof ProtectedBidsRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([AuthSignInRoute]),
  ProtectedRoute.addChildren([
    ProtectedBidsRouteRoute.addChildren([
      ProtectedBidsIdRoute,
      ProtectedBidsBidGenerationRoute,
      ProtectedBidsIndexRoute,
    ]),
    ProtectedIndexRoute,
  ]),
])

/* prettier-ignore-end */
